---
- name: Set Network Configurations
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Launch NTP Config include_role
      include_role:
        name: "network_ntp_config"  
      
  
    - name: Ensure SNMP settigs are defined
      ios_config:
        commands:
          - snmp-server community {{ snmp_ro_community }} RO
          - snmp-server community {{ snmp_rw_community }} RW

    - name: load new acl into device
      ios_config:
        lines: "{{ item }}"
        parents: ip access-list extended test
        # before: no ip access-list extended test
        match: exact
      with_items: "{{ acl_rules }}"
      
