---
- name: Set Network Configurations
  hosts: all
  connection: local
  gather_facts: false

  tasks:

    - name: Launch NTP Config include_role
      include_role:
        name: "network_ntp_config"  
      
  
    - name: Ensure SNMP settigs are defined
      ios_config:
        commands:
          - snmp-server community {{ snmp_ro_community }} RO
          - snmp-server community {{ snmp_rw_community }} RW

    - name: Ensre ACLs are set Correctly
      ios_config:
        lines: "{{ item }}"
      with_items: "{{ acl_rules }}"

    
